version: '3.0'

services:
  postgres:
    container_name: postgres
    image: postgres:15.3-alpine
    env_file:
      - ../.development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ../.development.env
    ports:
      - "8080:80"

  redis:
    image: redis:alpine
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASS"
    restart: unless-stopped
    env_file:
      - ../.development.env
    ports:
      - "6379:6379"

volumes:
  pgdata:
  staticdata:
